# Generated by Django 5.1.4 on 2024-12-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=15)),
                ('port', models.IntegerField(default=554)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('rtsp', 'RTSP'), ('http', 'HTTP')], default='rtsp', max_length=50)),
            ],
        ),
    ]
